BetterCMS/Models/MenuItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BetterCMS.Models
{
    public class MenuItemViewModel
    {
        public string Caption { get; set; }
        public string Url { get; set; }
        public bool IsActive { get; set; }

        public override string ToString()
        {
            return string.Format("Caption: {0}, Url: {1}", this.Caption, this.Url);
        }
    }
}

BetterCMS/Controllers/SiteMap2Controller.cs
using BetterCms.Module.Api;
using BetterCms.Module.Api.Operations.Pages.Sitemap;
using BetterCms.Module.Api.Operations.Pages.Sitemap.Tree;
using BetterCMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BetterCMS.Controllers
{
    public class SiteMap2Controller : Controller
    {
        private static Guid defaultSitemapId = new Guid("17ABFEE9-5AE6-470C-92E1-C2905036574B");

        //
        // GET: /SiteMap/
        public ActionResult Index(Guid actualPageId)
        {
            List<MenuItemViewModel> model = new List<MenuItemViewModel>();
            using (IApiFacade apiFacade = ApiFactory.Create())
            {
                Guid? sitemapId = this.GetSitemapId(apiFacade);
                if (sitemapId.HasValue)
                {
                    GetSitemapTreeRequest request = new GetSitemapTreeRequest
                    {
                        SitemapId = sitemapId.Value
                    };
                    GetSitemapTreeResponse getSitemapTreeResponse = apiFacade.Pages.Sitemap.Tree.Get(request);
                    if (getSitemapTreeResponse.Data.Count > 0)
                    {
                        model = (
                            from mi in getSitemapTreeResponse.Data
                            select new MenuItemViewModel
                            {
                                Caption = mi.Title,
                                Url = mi.Url,
                                IsActive = mi.PageId == actualPageId
                            }).ToList<MenuItemViewModel>();
                    }
                }
            }
            return base.View(model);
        }

        private Guid? GetSitemapId(IApiFacade api)
        {
            GetSitemapsResponse getSitemapsResponse = api.Pages.Sitemap.Get(new GetSitemapsRequest());
            if (getSitemapsResponse.Data.Items.Count > 0)
            {
                SitemapModel sitemapModel = getSitemapsResponse.Data.Items.FirstOrDefault((SitemapModel map) => map.Id == SiteMap2Controller.defaultSitemapId) ?? getSitemapsResponse.Data.Items.First<SitemapModel>();
                return new Guid?(sitemapModel.Id);
            }
            return null;
        }
    }
}

BetterCMS/Views/Blog/Feed.cshtml
@using BetterCms.Demo.Web.Models
@model IList<BlogItem>

@foreach (var item in Model)
{
    <div class="blog-box">
    <h4><a href="@item.Url">@item.Title</a></h4>
    <div class="blog-info clearfix">
        <span class="author">@item.Author</span>
        <time datetime="@item.PublishedOn.ToString("yyyy-MM-dd")">@item.PublishedOn.ToString("MMM d, yyyy")</time>
    </div>
    <a href="@item.Url"><img src="@item.ImageUrl" alt="Blog Feed Image"></a>
</div>
}

BetterCMS/Views/Blog/GetCategories.cshtml
@using BetterCms.Demo.Web.Models 
@model IList<CategoryItem>

@{
    var categoryId = Request.Params["categoryId"] ?? null;
}

<div class="submenu">
    <a href="@Request.Path" class="@(categoryId == null ? "submenu-active": null)">All</a>
    @foreach (var category in Model)
    {
        var active = categoryId != null && categoryId.ToUpper() == category.Id.ToString("D").ToUpper();
        <a href="@Request.Path?categoryId=@category.Id" class="@(active ? "submenu-active": null)">@category.Name</a>
    }
</div>

BetterCMS/Views/Blog/Index.cshtml
@using BetterCms.Demo.Web.Models
@model IList<BlogItem>

@foreach (var item in Model)
{
    <section class="blog-post">
        <h1><a href="@item.Url">@item.Title</a></h1>
        <span class="author">@item.Author</span><time datetime="@item.PublishedOn.ToString("yyyy-MM-dd")">@item.PublishedOn.ToString("MMM d, yyyy")</time>
        <span>
            @if (item.Tags != null) {
                foreach (var tag in item.Tags)
                {
                    <a href="@Request.Path?tagName=@tag" class="single-tag">@tag</a>
                }
            }
        </span>
        <article>
            <p>@Html.Raw(item.IntroText)</p>
            
            <a href="@item.Url">&lt; Read more &gt;</a>
        </article>
    </section>
}

BetterCMS/Views/Blog/Last.cshtml
@using BetterCms.Demo.Web.Models
@model BlogItem

<div class="side-box">
    <h2>@Model.Title</h2>
    <p>@Model.IntroText</p>
    <a href="@Model.Url">&lt; Read More &gt;</a>
</div>

BetterCMS/Views/Shared/Layouts/Light/Partial/_GalleryScripts.cshtml
<script src="@Url.Content("~/Scripts/gallery.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.coverflow.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.interpolate.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.mousewheel.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.touchSwipe.min.js")"></script>
    
<script type="text/html" id="gallery-template"><div class="gallery-view" id="images-gallery-container"></div>
    <div class="gallery-title" style="top: 408px;">
        <h1></h1>
        <h2></h2>
    </div>
    <div class="gallery-scrollbar">
        <div class="gallery-slider"></div>
    </div>
    <div id="gallery-thumbnails" class="thumbnails clearfix"></div>
</script>
    
<script type="text/html" id="gallery-thumbnail-template"><a><img src="" alt="" /></a></script>
<script type="text/html" id="gallery-image-modal-template"><div class='lightbox-image'><img alt='' src='' /></div></script>

BetterCMS/Views/Shared/Layouts/Light/_BlogPostLayout.cshtml
@using BetterCms.Module.Blog.Helpers.Extensions
@using BetterCms.Module.Pages.Helpers.Extensions
@using BetterCms.Module.Root.Mvc.Helpers

@{
    Layout = "~/Views/Shared/Layouts/Light/_LightTwoColumnsLayout.cshtml";
}

@{
    var authorName = string.Empty;
    var author = Model.GetBlogPostAuthorModel();
    if (author != null)
    {
        authorName = author.Name;
    }

    IList<string> tags;
    DateTime? date;
    if (Model.IsBlogPost())
    {
        date = Model.GetBlogPostModel().ActivationDate;
        tags = Model.GetPageTagsList();
    }
    else
    {
        date = null;
        tags = new List<string>();
    }
}


@model BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel

@section CMSMainContent {
    <section class="blogpost-head">
        <h1>@Model.Title<a onclick=" history.go(-1) " class="back-link">< Back</a></h1>
        <span class="author">@authorName</span>
        @if (date.HasValue)
        {
            <time datetime="@date.Value.ToString("yyyy-MM-dd")">@date.Value.ToString("MMM d, yyyy")</time>
        }
        @if (tags != null && tags.Count > 0)
        {
            var blogListUrl = Model.GetOptionValue<string>("Blogs List Page URL");
            if (!string.IsNullOrEmpty(blogListUrl))
            {
                <span>
                    @foreach (var tag in tags)
                    {
                        <a href="@blogListUrl?tagName=@tag" class="single-tag">@tag</a>
                    }
                </span>
            }
        }
    </section>

    @RenderSection("CMSMainContent", false)
}

@section ColRight {
    @RenderSection("ColRight", false)
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCMS/Views/Shared/Layouts/Light/_ContactsLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml";
}

@section MainContent {
    <div class="contact-info clearfix">
        <div class="clearfix">
            <div class="contact-address">
                @RenderSection("Address", false)
            </div>

            <div class="contact-social">
                @RenderSection("Social", false)                
            </div>
        </div>

        <div class="contact-map">
            @RenderSection("Map", false)
        </div>
    </div>

    <div class="contact-form">
        @RenderSection("Form", false)
    </div>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCMS/Views/Shared/Layouts/Light/_GalleryLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml";
}

@section HeadScripts {
    <link href="/Content/Styles/bcms.light.gallery.css" rel="stylesheet" />
    
    @RenderSection("HeadScripts", false)
}

@section MainContent {
    <div id="gallery-main-content" style="visibility: hidden;">
        @RenderSection("MainContent", false)
    </div>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
    @Html.Partial("Layouts/Light/Partial/_GalleryScripts")
    <script src="@Url.Content("~/Scripts/gallery.gallery.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.lightbox_me.js")"></script>
}

BetterCMS/Views/Shared/Layouts/Light/_HomeLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml";
}

@section MainContent {
    <section class="home-banner" id="home-slides">
        @RenderSection("Slider", false)
    </section>
    
    <div class="home-bottom">
        <article>
            @RenderSection("Article", false)
        </article>
        
        <section class="home-gallery">
            <div id="gallery-main-content" style="visibility: hidden;">
                @RenderSection("SideBar", false)
            </div>
        </section>
    </div>
}

@section HeadScripts {
     <link href="/Content/Styles/bcms.light.gallery.css" rel="stylesheet" />
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
    @Html.Partial("Layouts/Light/Partial/_GalleryScripts")
    <script src="@Url.Content("~/Scripts/gallery.home.js")"></script>
}

BetterCMS/Views/Shared/Layouts/Light/_LightLayout.cshtml
@*@using BetterCms.Demo.Web*@

@{ Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml"; }


@section HeadScripts {
    <meta charset="utf-8" />
    <link href="/Content/Styles/bcms.light.layout.css" rel="stylesheet" />
    <link href="/Content/Styles/bcms.light.content.css" rel="stylesheet" />
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/modernizr.js")"></script>
    <![endif]-->

    @RenderSection("HeadScripts", false)
}

@section Scripts {
    <script src="//codeorigin.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="@Url.Content("~/Scripts/onload.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>
    <script src="@Url.Content("~/Scripts/validation.extenders.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.accordion.js")"></script>
    <script src="@Url.Content("~/Scripts/slides.min.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/messages.js")"></script>
    <script src="@Url.Content("~/Scripts/forms.js")"></script>

    @RenderSection("Scripts", false)
}

<div class="page">
    <header class="page-header">
        <div class="page-frame clearfix">
            <a href="/" class="logo">
                <img src="/Content/images/logo.png" alt="BetterCMS" />
            </a>
            <nav class="page-navigation" id="site-nav">
                @{ Html.RenderAction("Index", "SiteMap", new { area = "" }); }
            </nav>
        </div>
    </header>

    <div class="page-block">

        <div class="default-messages-container">
            <div class="error-user-message-container">
                <ins class="icon-static"></ins>
                <div class="error user-message">
                </div>
            </div>
            <div class="success-user-message-container">
                <ins class="icon-static"></ins>
                <div class="success user-message">
                </div>
            </div>
        </div>

        <div class="page-frame clearfix">
            @RenderSection("MainContent", false)
            @RenderBody()
        </div>
    </div>

</div>

<footer class="page-footer">
    <div class="page-frame clearfix">
        <span class="copyright">&copy; @DateTime.Now.Year Better CMS</span>
    </div>
</footer>

BetterCMS/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightLayout.cshtml";
}

@section HeadScripts {
    @RenderSection("HeadScripts", false)
}


@section MainContent {
    @RenderSection("MainContent", false)
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCMS/Views/Shared/Layouts/Light/_LightThreeColumnsLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightLayout.cshtml";
}

@section MainContent {
    <section class="three-col-left">
        @RenderSection("MainContent", false)
    </section>
    
    <section class="three-col-middle">
        @RenderSection("ColMiddle")
    </section>
    
    <aside class="col-right">
        @RenderSection("ColRight", false)
    </aside>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCMS/Views/Shared/Layouts/Light/_LightTwoColumnsLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightLayout.cshtml";
}

@section MainContent {
    <section class="two-col-left">
        @RenderSection("CMSMainContent", false)
    </section>
    
    <aside class="col-right">
        @RenderSection("ColRight", false)
    </aside>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCMS/Views/SiteMap2/Index.cshtml
@model IList<BetterCMS.Models.MenuItemViewModel>

@foreach (var item in Model)
{
    <li @if (item.IsActive) { <text> class="active" </text>  }><a href="@item.Url">@item.Caption</a></li>
}

BetterCMS/Views/SiteMap2/SubMenu.cshtml
@using BetterCms.Models
@model IList<MenuItemViewModel>

<div class="submenu">
    @foreach (var item in Model)
    {
        <a href="@item.Url" class="@(Request.Path == item.Url ? "submenu-active": null)">@item.Caption</a>
    }
</div>

BetterCMS/Views/Templates/GeoTemplate.cshtml
@*
    How to create a page template?
    http://www.bettercms.com/documentation/templates
    http://www.devbridge.com/articles/better-cms-for-developers/    
*@

@using BetterCms.Module.Blog.Helpers.Extensions
@using BetterCms.Module.Pages.Helpers.Extensions

@model BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel

@{
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";
}

<h2>GeoLayout</h2>
<p>@Model.Title</p>
<p>@Model.Id</p>

<div>
    @RenderSection("CmsContent", false)
</div>

BetterCMS/Views/Templates/StyritContent.cshtml
@{
    Layout = "~/Views/Templates/StyritMaster.cshtml";
}

@section MainContent {
    <section class="container">
        <div class="row">
            <article class="span12">
                <br />
                @RenderSection("CmsContent", false)
            </article>
        </div>
        @*<hr class="soft" />*@
    </section>
}

@*@RenderBody()*@

BetterCMS/Views/Templates/StyritHome.cshtml
@{
    Layout = "~/Views/Templates/StyritMaster.cshtml";
}

@section MainContent {
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="span7">
                    @RenderSection("HeaderContentLeft", false)
                </div>
                <div class="offset1 span4 center">
                    @RenderSection("HeaderContentReight", false)
                </div>
            </div>
        </div>
    </header>

    <section class="container">
        <div class="row">
            <article class="span12">
                <br />
                @RenderSection("CmsContent", false)
            </article>
        </div>
        @*<hr class="soft" />*@
    </section>
}

@*@RenderBody()*@

BetterCMS/Views/Templates/StyritMaster.cshtml
@*
    How to create a page template?
    http://www.bettercms.com/documentation/templates
    http://www.devbridge.com/articles/better-cms-for-developers/
*@

@using BetterCms.Module.Blog.Helpers.Extensions
@using BetterCms.Module.Pages.Helpers.Extensions

@model BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel

@{
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";
}

@section HtmlTag
{
    <!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
    <!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
    <!--[if !IE]><!-->
    <html lang="en">
    <!--<![endif]-->
}

@section HeadScripts {

}

@section Styles
{
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Styrit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/Assets/Styrit/img/favicon.png" type="image/png" />
    <link rel="stylesheet" href="~/Assets/Styrit/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="~/Assets/Styrit/css/m-buttons.css" type="text/css" />
    <link rel="stylesheet" href="~/Assets/Styrit/css/m-icons.css" type="text/css" />
    <link rel="stylesheet" href="~/Assets/Styrit/css/styles.css" type="text/css" />
}

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a href="/" class="brand">Styrit <i class="m-icon-big-styrit"></i></a>
            <ul class="nav">
                @*<li class="active"><a href="#">Home </a></li>
                    <li><a href="#">Support</a></li>
                    <li><a href="#">Company</a></li>*@

                @{ Html.RenderAction("Index", "SiteMap2", new { actualPageId = Model.PageData.Id }); }

            </ul>
        </div>
    </div>
</div>

@RenderSection("MainContent", false)
@*@RenderBody()*@

@*
    <section class="container">
        <div class="row">
            <div class="span12 center newsletter-box">
                <div class="row">
                    <form class="form-inline">
                        <p>
                            Get the latest updates about <strong>MySurfaceApp</strong>. Join our mailing list!
                        </p>

                        <input type="text" placeholder="Your email address.." />
                        <button type="submit" class="btn">Notify Me! <i class="icon-envelope"></i></button>

                    </form>
                </div>
            </div>
        </div>
    </section>

    <footer class="container">
        <div class="row">
            <div class="span2">
                <p>
                    <strong>Company</strong>
                </p>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Team</a></li>
                </ul>
            </div>
            <div class="span2">
                <p>
                    <strong>MySurfaceApp</strong>
                </p>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Support</a></li>
                    <li><a href="#">Features</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </div>
            <div class="span8">
                <p class="pull-right">Designed by Ace Subido. </p>
            </div>
        </div>
    </footer>
*@

BetterCMS/Views/Widgets/BlogFeedWidget.cshtml
@{ Html.RenderAction("Feed", "Blog", new { area = string.Empty }); }

BetterCMS/Views/Widgets/CategoriesMenuWdiget.cshtml
@{ Html.RenderAction("GetCategories", "Blog", new { area = string.Empty }); }

BetterCMS/Views/Widgets/ContactFormWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@model BetterCms.Demo.Web.Models.ContactFormViewModel

@{ Model.EmailTo = OptionsHelper.GetValue(Model.Options, "EmailToAddress"); }

@using (Html.BeginForm("ContactForm", "Contact", FormMethod.Post, new { @class = "autobind" }))
{
    <h2>Contact Us</h2>

    <div class="field-holder">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "text-field" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="field-holder">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "text-field" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>

    <div class="field-holder">
        @Html.LabelFor(m => m.Message)
        @Html.TextAreaFor(m => m.Message, new { @class = "text-area", style="height: 232px;" })
        @Html.ValidationMessageFor(m => m.Message)
    </div>
    
    @Html.HiddenFor(m => m.EmailTo)
    <a class="btn-primary" data-url="/contacts/submit-form">Send</a>
}

BetterCMS/Views/Widgets/GeoWidget.cshtml
@*
    http://www.bettercms.com/documentation/widgets
*@

@model BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel

@if (Model != null)
{
    <h2>Widget Name: @Model.Widget.Name</h2>
    <h3>Current Page: @Model.Page.PageUrl</h3>
    <p>Some widget content...</p>
}
else
{
    <p>Widget Preview...</p>
}

BetterCMS/Views/Widgets/LastBlogPostWidget.cshtml
@{ Html.RenderAction("Last", "Blog", new { area = string.Empty }); }

BetterCMS/Views/Widgets/LatestBlogPostsWdiget.cshtml
@{ Html.RenderAction("Index", "Blog", new { area = string.Empty }); }

BetterCMS/Views/Widgets/MenuWidget.cshtml
@using BetterCms.Sandbox.Mvc4.Helpers
@{
//    var languageCode = OptionsHelper.GetValue(Model.Options, "languageCode");
//    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = languageCode });

    <strong>Sitemap API test:</strong>
    <p>Lithuanian:</p>
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = "lt" });
    <p>English:</p>
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = "en" });
    <p>Default:</p>
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = "default" });
    
    <p>As inserted to the sitemap:</p>
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty });
}

BetterCMS/Views/Widgets/Options.cshtml
@model BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel
@if (Model != null)
{
    <h2>Widget Name: @Model.Widget.Name</h2>
    <h3>Current Page: @Model.Page.PageUrl</h3>
}
else
{
    <p>Widget Preview...</p>
}

@if (Model != null && Model.Options != null)
{
    foreach (var option in Model.Options)
    {
        <strong>Option "@option.Key" Type:</strong> @(option.Value != null ? option.Value.GetType().ToString() : string.Empty)
        <strong>; Value: </strong> @option.Value <br />
    }
}

BetterCMS/Views/Widgets/SocialWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@using BetterCms.Module.Root.ViewModels.Cms
@model RenderWidgetViewModel

@{
    var useSideBoxOption = OptionsHelper.GetValue(Model.Options, "useSideBox");
    var useSideBox = !string.IsNullOrWhiteSpace(useSideBoxOption) && Convert.ToBoolean(useSideBoxOption);
}

@if (useSideBox)
{
    @:<div class="side-box">
}

<h2>@Html.TitleForSocial()</h2>

<div class="social-logo clearfix">
    @Html.LinkForSocial("facebookShouldRender", "facebookUrl", "facebookTitle", "facebookCssClass")
    @Html.LinkForSocial("twitterShouldRender", "twitterUrl", "twitterTitle", "twitterCssClass")
    @Html.LinkForSocial("linkedinShouldRender", "linkedinUrl", "linkedinTitle", "linkedinCssClass")
</div>
<div class="social-logo clearfix">
    @Html.LinkForSocial("skypeShouldRender", "skypeUrl", "skypeTitle", "skypeCssClass")
    @Html.LinkForSocial("youtubeShouldRender", "youtubeUrl", "youtubeTitle", "youtubeCssClass")
    @Html.LinkForSocial("flickrShouldRender", "flickrUrl", "flickrTitle", "flickrCssClass")
</div>

@if (useSideBox)
{
    @:</div>
}

BetterCMS/Views/Widgets/SubMenuWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@{
    var parentUrl = OptionsHelper.GetValue(Model.Options, "parentUrl");
    if (parentUrl != null)
    {
        Html.RenderAction("SubMenu", "Sitemap", new { area = string.Empty, parentUrl = parentUrl });        
    }
}